- name: Deploy via FTP com npm
  run: |
    npm install -g basic-ftp
    node -e "
      const ftp = require('basic-ftp');
      (async () => {
        const client = new ftp.Client();
        client.ftp.verbose = true;
        try {
          await client.access({
            host: process.env.FTP_HOST,
            user: process.env.FTP_USERNAME,
            password: process.env.FTP_PASSWORD,
            port: 21
          });
          await client.ensureDir(process.env.FTP_REMOTE_DIR);
          await client.clearWorkingDir();
          await client.uploadFromDir('dist/stock-web');
        } catch(err) {
          console.error(err);
          process.exit(1);
        }
        client.close();
      })();
    "
  env:
    FTP_HOST: ${{ secrets.FTP_HOST }}
    FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
    FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
